@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM0NzA2MTA0LCJpYXQiOjE3MzQ2ODgxMDQsImp0aSI6IjIxNzc3YmQ0YmRlMzQwNzI5YzEyNjQxYWQ3NjYxZjNjIiwidXNlcl9pZCI6OH0.6qQoTpP7wMe9LukcTLMhuaWN1jW0yh6DckOeIxK_A7w

## Add new Column
POST http://localhost:8000/api/kanban_board/kanban_column/
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "workspace_id": 10,
    "name": "Progress"
}
###

## Get all Columns
GET http://localhost:8000/api/workspaces/columns/?workspace_id=18
Authorization: Bearer {{token}}
###

## Update Column
PUT http://localhost:8000/api/kanban_board/2/
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Done updated"
}
###

## Delete Column
DELETE http://localhost:8000/api/kanban_board/5/
Authorization: Bearer {{token}}


Card --------------------------------------------------------------------

## Add new Card

###
POST http://localhost:8000/api/kanban_board/kanban_card/
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "column_id": 8,
    "content" : "Card3",
    "due_date": "2021-10-10",
    "assign": 6
}
###

## Get all Cards
GET http://localhost:8000/api/kanban_board/kanban_card/?column_id=21
Authorization: Bearer {{token}}
###

## Update Card

PUT http://localhost:8000/api/kanban_board/kanban_card/38/
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "content": "Car2 updated",
    "due_date": "2021-10-10"
}
###

## Delete Card
DELETE http://localhost:8000/api/kanban_board/kanban_card/2/
Authorization: Bearer {{token}}












