# @token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMzMjExNjI2LCJpYXQiOjE3MzMxOTM2MjYsImp0aSI6IjQ2NjQ3MjRmMGI3MTRjODNhODE3ZmE5NDZjZjZhMzBjIiwidXNlcl9pZCI6NH0.VVpI5VnFVc0hz7mDXqejd3oZMR2jPDC0ygikzB4g0Zk
@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM0MzQ4OTIxLCJpYXQiOjE3MzQzMzA5MjEsImp0aSI6IjJkYWRhYzY5ZTI5NTQ0NjJiMWJlMjY3NDFjMTIwOTM1IiwidXNlcl9pZCI6OH0.yb2mQcvbISMf_5pYlKwZj8QXJc2Hkwud5cdPPr-RQ7A

## Add new Workspace
POST http://localhost:8000/api/workspaces/
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "viet7 new1",
    "icon_unified": "icon_1"
}
###

## Get all Workspaces
# **Note**: You can filter by role, for example: owner or member
GET http://localhost:8000/api/workspaces/?role=owner
Authorization: Bearer {{token}}
###

## Delete Workspace
DELETE http://localhost:8000/api/workspaces/6/
Authorization: Bearer {{token}}
###

## Get Workspace by ID
# GET http://localhost:8000/api/workspaces/14/
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMzMTQxNTQ0LCJpYXQiOjE3MzMxMjM1NDQsImp0aSI6ImZlNTcyZWRlNzNmODQwYTVhOTNhNzk2YTQ5MzRkNGNkIiwidXNlcl9pZCI6Mn0.s3GV5dyu2yBfNtR6QwvCA3HB7m7cHIZ7-2MFyUPWpL0
###

## Update Workspace
PUT http://localhost:8000/api/workspaces/6/
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Viet",
    "icon_unified": "icon_1"
}
###