@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMzMzk5NDc3LCJpYXQiOjE3MzMzODE0NzcsImp0aSI6IjQ5MTJhYzM4MGZlOTRmOGJiN2JkMWYzMzgyZjlmMTk0IiwidXNlcl9pZCI6MX0.KiIzJizfYUjcTE4S7V5ZaejhDSmX2BjWat7b3m9Cqz8
# Workspace --------------------------------------------------------------------

## Add new Workspace
POST http://localhost:8000/api/workspaces/
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "School",
    "icon_unified": "icon_1"
}
###

## Get all Workspaces
# **Note**: You can filter by role, for example: owner or member
GET http://localhost:8000/api/workspaces/?role=owner
Authorization: Bearer {{token}}
###

## Delete Workspace
DELETE http://localhost:8000/api/workspaces/1/
Authorization: Bearer {{token}}
###

## Get Workspace by ID
# GET http://localhost:8000/api/workspaces/14/
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMzMTQxNTQ0LCJpYXQiOjE3MzMxMjM1NDQsImp0aSI6ImZlNTcyZWRlNzNmODQwYTVhOTNhNzk2YTQ5MzRkNGNkIiwidXNlcl9pZCI6Mn0.s3GV5dyu2yBfNtR6QwvCA3HB7m7cHIZ7-2MFyUPWpL0
###

## Update Workspace
PUT http://localhost:8000/api/workspaces/1/
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Update",
    "icon_unified": "icon_1"
}
###
